/**
 * Pre-built half-block terminal art from PNG (I-97) — generated by build-pet-assets.py.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { resolvePetDir } from "./petAssets.js";
import type { PetState, PetTheme } from "./petState.js";

export interface PetTerminalSegment {
  t: string;
  f?: string | null;
  b?: string | null;
}

export interface PetTerminalArtFrame {
  lines: PetTerminalSegment[][];
}

export interface PetTerminalArtFile {
  version: number;
  width?: number;
  frames: PetTerminalArtFrame[];
}

const artCache = new Map<string, PetTerminalArtFile | null>();

function cacheKey(petDir: string, state: PetState, theme: PetTheme): string {
  return `${petDir}\0${state}\0${theme}`;
}

export function loadPetTerminalArt(
  petDir: string,
  state: PetState,
  theme: PetTheme = "light"
): PetTerminalArtFile | null {
  const key = cacheKey(petDir, state, theme);
  if (artCache.has(key)) return artCache.get(key) ?? null;

  const path = join(petDir, "terminal", theme, `${state}.json`);
  if (!existsSync(path)) {
    artCache.set(key, null);
    return null;
  }
  try {
    const raw = JSON.parse(readFileSync(path, "utf8")) as PetTerminalArtFile;
    if (!Array.isArray(raw.frames) || raw.frames.length === 0) {
      artCache.set(key, null);
      return null;
    }
    artCache.set(key, raw);
    return raw;
  } catch {
    artCache.set(key, null);
    return null;
  }
}

export function resolvePetTerminalArt(
  dir: string,
  state: PetState,
  theme: PetTheme = "light"
): PetTerminalArtFile | null {
  const petDir = resolvePetDir(dir);
  if (!petDir) return null;
  return loadPetTerminalArt(petDir, state, theme);
}

export function petTerminalArtFrame(
  art: PetTerminalArtFile,
  tick: number
): PetTerminalArtFrame {
  const frames = art.frames;
  const idx = frames.length > 1 ? tick % frames.length : 0;
  return frames[idx]!;
}
